config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: 'games#index'

  resources :games, only: %i[index show create destroy update] do
    member do
      patch :play_again
      patch :choose
      patch :start
    end
  end

  get '*path' => redirect('/')
end

app/models/game.rb
class Game < ApplicationRecord
  include ActiveModel::Validations
  include ActiveModel::Validations::Callbacks

  has_many :rooms, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_one :hero, dependent: :destroy
  belongs_to :user
  validates_associated :user
  validates_with BooleanOverStart
  before_save :max_games_number

  MONSTERS = ["Python serpent", "Java owlbear", "C# troll", "PHP-gnoll"]
  BOSS = ["Go Lord"]
  CHOICE = ["bridge", "grail"]
  TREASURES = ["Pair of Climbing Shoes 👟", "MacBook 💻"]
  EMPTY = %w(None) * 6
  UPPER_WALL = [1, 2, 3, 4]
  LOWER_WALL = [13, 14, 15, 16]
  LEFT_WALL  = [1, 5, 9, 13]
  RIGHT_WALL = [4, 8, 12, 16]
  ROOM_MOVEMENT = { "UP" => -4, "DOWN" => 4, "LEFT" => -1, "RIGHT" => 1 }
  MESSAGES = { empty: ["This room is empty - Nothing to see here..."],
               fight_boss: ["You've encountered you Nemesis, the dreadful Go Lord 👹.", "Time to fight!"], 
               victory: ["Congratulations, you won.", "These languages were no match for your Ruby sword, and your Rails armour!"],
               defeat: ["Gravely wounded, you have to retreat.", "But you know you'll be back. Hasta la vista babe."] }
  SCENARII = { bridge: {
                  description: ["You're facing the Bridge of Death 💀.", "A blind guardian asks you: 'There are 10 types of people.'", "'Which are you ?'"],
                  choices: ["Those who get ternary.", "Those who don't.", "Those who thought this was going to be a binary joke."],
                  positive_msg: ["You've crossed the bridge.", "The guardian, happy with your answer, gives you a kettlebell.", "You train and earn +5 strength 💪."],
                  negative_msg: ["You've crossed the bridge, but the guardian, unhappy, shot you in the face.", "As he's visually impaired, he only got your shield arm.",  "You lost 2 defense 🤢."],
                  valid_choices: ['1', '3'],
                  consequence: { success: { strength: 5 }, failure: { defense: -2} }
                },
                grail: {
                  description: ["You've found 3 full cups 🏺.", "All doors are closed, and you understand that you need to drink from one of them.", " Which one will you choose?"],
                  choices: ["The cup decorated with diamonds.", "The cup decorated with rubies.", "The simple cup."],
                  positive_msg: ["The doors open, and you feel great.", "You've healed and earned 10 health points 🩹."],
                  negative_msg: ["The doors open, but you feel weak.", "You've lost 3 strength 🤢."],
                  valid_choices: ['2'],
                  consequence: { success: { health: 10 }, failure: { strength: -3} }
                }
              }
  
  def start_setup
    create_rooms
    create_hero
    Event.new(self, nil).add_message("Move to start your adventure.")
  end

  def generate_board
    board_array = []
    sorted_board(rooms).each do |room|
      board_array << symbol(room)
    end
    board_array
  end

  def avalaible_commands
    commands = {}
    hero_room_base_16 = hero.room_number -  sorted_board(rooms).first.id + 1

    commands[:up]    = !UPPER_WALL.include?(hero_room_base_16)
    commands[:right] = !RIGHT_WALL.include?(hero_room_base_16)
    commands[:down]  = !LOWER_WALL.include?(hero_room_base_16)
    commands[:left]  = !LEFT_WALL.include?(hero_room_base_16)
    

    commands
  end

  def symbol(room)
    return '  '  if room.encounter == "None" && !room.visited
    return '❌'  if room.encounter == "None" && room.visited
    return '🐺' if MONSTERS.include?(room.encounter)
    return '🔮' if CHOICE.include?(room.encounter)
    return '💰' if TREASURES.include?(room.encounter)
    return '👹'  if BOSS.include?(room.encounter)
    '🦸' # Hero if non empty room with no opponent, choice or treasure
  end

  def start_adventure
    update(start: false)
  end

  def clean_hero_room
    former_room = rooms.find(hero.room_number)
    former_room.update(encounter: "None", visited: true)
  end

  def update_hero_room(command)
    new_hero_room = hero.room_number + ROOM_MOVEMENT[command]
    hero.update(room_number: new_hero_room) # Change hero room
    update_event(rooms.find(new_hero_room)) # Deals with encounter
    rooms.find(hero.room_number).update(encounter: "Hero") unless !hero.alive # Add hero symbol to new room unless he died this turn
  end

  def resolve_choice(num)
    Event.new(self, nil, num).choice_consequence
    update(choice: nil) # Deleting this choice
    check_alive
  end

  private
    def create_rooms
      rooms_content = design_balanced_rooms
      rooms_content.each { |content| rooms.create(encounter: content, visited: false) } # Create them
      rooms.create(encounter: "Hero", visited: false) # Populate last room with hero
    end

    def create_hero
      self.hero = Hero.create(alive: true, health: 50, strength: 10, defense: 5, experience: 5, room_number: rooms.last.id)
    end

    def sorted_board(rooms)
      rooms.sort_by { |room| room.id }
    end

    def design_balanced_rooms
      result = []
      loop do
        result = (MONSTERS + BOSS + CHOICE + TREASURES + EMPTY).shuffle # Shuffle 15 non starting rooms
        break unless result.each_slice(4).to_a[0, 3].any? { |arr| arr.uniq.size == 1 } # Recreate rooms if line 1, 2, or 3 has no encounter at all.
      end
      result
    end

    def max_games_number
      return if user.games.count < 3
      errors.add :base, "Can't have more than 3 games"
      false
    end

    def is_boolean?(el)
      el.is_a?(TrueClass) || el.is_a?(FalseClass)
    end

    def update_event(room)
      Event.new(self, room).play_event
      check_alive
    end

    def check_alive
      if hero.health <= 0
        hero.update(alive: false)
        Event.new(self).end_game
      end
    end

    class Event
      def initialize(game, room = nil, num = nil)
        @game = game
        @hero = @game.hero
        @encounter = room.encounter if room
        @choice_num = num
        @visited = room.visited if room
      end

      def play_event
        case 
        when (MONSTERS + BOSS).include?(@encounter) then fight
        when (TREASURES).include?(@encounter) then treasure
        when (CHOICE).include?(@encounter) then choice
        else @visited ? visited_room : add_message(MESSAGES[:empty], true)
        end
      end

      def choice_consequence
        scenario = SCENARII[@game.choice.to_sym]
        if scenario[:valid_choices].include?(@choice_num)
          add_message(scenario[:positive_msg], true)
          hash = scenario[:consequence][:success]
        else
          add_message(scenario[:negative_msg], true)
          hash = scenario[:consequence][:failure]
        end

        carac = hash.keys.first # Carac to be modified
        new_value = @hero.send(carac) + hash.values.first # Bonus or malus to carac.

        @hero.update({ hash.keys.first => new_value })
      end

      def add_message(msg, array = false, br = true)
        messages = array ? msg : [msg]
        messages.each { |message| @game.messages.create(body: message) }
        @game.messages.create(body: "br") if br # Skip a line by default after adding series of messages.
      end

      def end_game(defeat = true)
        msg = defeat ? MESSAGES[:defeat] : MESSAGES[:victory]
        add_message(msg, true)
        @game.update(over: true)
      end

      private

        def visited_room
          num = [rand(10) + 1, @hero.health].min # Can't lose more HP than current HP.
          new_health = @hero.health - num
          @hero.update(health: new_health)

          messages = ["You already visited this room.", "A Ruby Dev should know better: Don't Repeat Yourself!", "Ashamed, you lost #{num} health points 🩸."]

          add_message(messages, true)
        end

        def fight
          battle_loop
        end

        def treasure
          carac = ["defense", "strength"].sample
          symbol = carac == "defense" ? '🛡' : '🔪'
          value = rand(10) + 1
          add_message(["You've opened the chest, and found an Epic #{@encounter}.", "Every good Ruby dev needs one.", "You've increased your #{carac} by #{value} #{symbol}."], true)
          carac == "defense" ? @hero.update(defense: @hero.defense + value) : @hero.update(strength: @hero.strength + value)
        end
    
        def choice
          dilemma = SCENARII[@encounter.to_sym]
          @game.update(choice: @encounter)
          add_message(dilemma[:description], true)
          dilemma[:choices].each_with_index do |choice, idx|
            add_message("#{idx + 1}: #{choice}")
          end
        end

        def add_xp(new_xp)
          @hero.update(experience: @hero.experience + new_xp)
        end

        def battle_loop
          fighters = [Fighter.new(@hero), Fighter.new(@encounter)]
          current_fighter = fighters.first
          other_fighter = fighters.last

          str = @encounter == "Go Lord" ? MESSAGES[:fight_boss] : ["You've encountered a #{@encounter} 🐺.", "Time to fight !"]
          add_message(str, true) #Presentation of opponent

          until fighters.any?(&:dead?)
            current_fighter.harm(other_fighter)
            add_message("#{current_fighter.symbol} 🔪 attacks 🛡  #{other_fighter.symbol} (health ❤️  #{[other_fighter.health, 0].max})", false, false)
            other_fighter.actualize_hero_stats if other_fighter.symbol == '🦸'
            current_fighter, other_fighter = other_fighter, current_fighter
          end

          add_message("br", false, false) # Skip a line after combat loop.
          
          if @hero.health > 0 # Hero won the fight
            combat_xp = @encounter == "Go Lord" ? 20 : 5
            add_xp(combat_xp)
            add_message(["You've vanquished the #{@encounter}!", "You've earned #{combat_xp} points of experience ✊."], true)
            end_game(false) if @encounter == "Go Lord" # Over if killed boss
          end
        end
    end

    class Fighter

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_games, only: [:new, :index]
  
  def index
  end

  def show
    find_game
    @board = @game.generate_board
    @commands = @game.avalaible_commands
  rescue ActiveRecord::RecordNotFound
    flash[:danger] = "You don't have access to this game."
    redirect_to root_path
  end

  def create(new = true)
    @game = current_user.games.new(over: false, start: new) # No pre-start screen if game created with the "Play Again" button.
    if current_user.games.count < 3 && @game.save
      flash[:success] = "And so your adventure begins. May you critical hit your way to the end!"
      @game.start_setup
      redirect_to @game
    else
      flash[:danger] = "No more than 3 games."
      set_games
      redirect_to root_path
    end
  end

  def destroy
    find_game
    @game.destroy

    redirect_to root_path
  end

  def update
    find_game
    clean_messages
    @game.clean_hero_room
    @game.update_hero_room(params[:commit])
    redirect_to @game
  end

  def choose
    find_game
    clean_messages
    @game.resolve_choice(params[:commit][-1])
    redirect_to @game
  end

  def start
    find_game
    @game.start_adventure
    redirect_to @game
  end

  def play_again
    find_game
    @game.destroy
    set_games
    if @games.size > 0
      redirect_to root_path
    else
      create(false)
    end
  end

  private

    def set_games
      @games = current_user.games.all.sort_by { |game| game.updated_at }.reverse
    end

    def find_game
      @game = current_user.games.find(params[:id])
    end

    def clean_messages # Clean all old messages after moving or making a choice
      @game.messages.each { |message| message.destroy }
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_board.html.erb
<table class="table board-table emoticone">
  <% @board.each_slice(4) do |line| %>
    <tr>
      <% line.each do |symbol| %>
        <td><div class="content"><%= symbol %></div></td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/games/_choices.html.erb
<%= form_for @game, url: {action: "choose"} do |form| %>
  <div class="commands">
    <% (1..3).each do |idx| %>
      <div class="command">
        <p class="dungeon"><%= form.submit "CHOICE #{idx}" %></p>
      </div>
    <% end %>
  </div>
<% end %>

app/views/games/_commands.html.erb
<%= form_with model: @game do |form| %>
  <div class="commands">
    <% @commands.each do |key, boolean| %>
      <% if boolean %>
        <p class="dungeon command"><%= form.submit "#{key.to_s.upcase}" %></p>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/games/_debug.html.erb
<%# Onlys use if need to debug the board %>
<ul>
  <p>Game.id: <%= @game.id %></p>
  <p>Games.rooms.last.id: <%= @game.rooms.last.id %></p>
  <p>Games.rooms.first.id: <%= @game.rooms.first.id %></p>
  <p>Hero.id: <%= @game.hero.id %></p>
  <p>Hero.room: <%= @game.hero.room_number %></p>
</ul>
<br>
<ul>
  <li>
    <% @game.rooms.each do |room| %>
      <p>Id: <%= room.id %> Encounter: <%= room.encounter %> Visited?: <%= room.visited %></p>
    <% end %>
  </li>
</ul>

app/views/games/_game_over.html.erb
<%= form_for @game, url: {action: "play_again"} do |form| %>
  <div class="commands">
    <p class="dungeon command"><%= form.submit "PLAY AGAIN" %></p>
  </div>
<% end %>

app/views/games/_games.html.erb
 <div class="dungeon">
  <% if @games.size < 3 %>
    <p>Start a 
      <%= link_to "new game", games_path, method: :post %>
    and live an exciting adventure!</p>
  <% else %>
    <p>No more free slots. You must delete a game before you start a new one.</p>
  <% end %>
  
  <% if @games.size > 0 %>
    <br>
    <p>Or load a saved game:</p>
    <ul>
      <% @games.each do |game| %>
        <br>
        <li><p>Last played on <%= game.updated_at.strftime("%F at %H:%M") %></p>
          <ul>
            <li>
              <p><%= link_to "Play", game %></p>
            </li>
            <li>
              <p><%= link_to "Delete", game,
                      method: :delete,
                      data: { confirm: "Are you sure?" } %></p>
            </li>
          </ul>
        </li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/games/_messages.html.erb
<ul class="messages">
  <br>
  <% @game.messages.each do |message| %>
    <% if message.body == "br" %>
      <br>
    <% else %>
      <li>
        <p class="dungeon animation"><%= message.body %></p>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/games/_presentation.html.erb
<div class="dungeon animation">  
  <p>Welcome to the epic world or Ruby & Rails Dungeon 💎🚊🏰. It's like Dungeons & Dragons 🐲🏰, but with bad binary jokes 🤓.</p>
  <br>
  <p>You (🦸) are a young Ruby dev, looking for an adventure. You must fight your archnemesis (👹), but you probably should train a bit before that ✊.</p>
  <br>

  <p>In this dungeon, you can encounter:</p>
  <p>- 🐺 : Non Ruby problems (solve them to gain in experience)</p>
  <p>- 💰 : Stock options (sell them before the next recession)</p>
  <p>- 🔮 : Choices (choose wisely)</p>
  <br>

  <p>Explore the dungeon, win XP, defeat the evil Go Lord, and, most of all, Don't Repeat Yourself ❌!</p>
  <br>

  <%= form_for @game, url: {action: "start"} do |form| %>
    <div class="commands">
      <br>
      <p class="command"><%= form.submit "START" %></p>
    </div>
  <% end %>
</div>

app/views/games/_stats.html.erb
<table class="table dungeon board-table">
  <tr>
    <th colspan="4"><p class="table_title">STATS</p></th>
  </tr>
  <tr>
    <td><p>HP</p></td>
    <td><p>STR</p></td>
    <td><p>DEF</p></td>
    <td><p>XP</p></td>
  </tr>
  <tr>
    <td><p>❤️</p></td>
    <td><p>🔪</p></td>
    <td><p>🛡</p></td>
    <td><p>✊</p></td>
  </tr>
  <tr>
    <td><p><%= @game.hero.health %></p></td>
    <td><p><%= @game.hero.strength %></p></td>
    <td><p><%= @game.hero.defense %></p></td>
    <td><p><%= @game.hero.experience %></p></td>
  </tr>
</table>

app/views/games/_title.html.erb
<h1 class="dungeon">💎 Ruby & Rails Dungeon 🏰</h1>

app/views/games/index.html.erb
<div class="dungeon">
  <% if current_user.present? %>
    <h1>Welcome, <%= current_user.name %></h1>
    <br>
    <%= render "games", object: @games %>
  <% else %>
    <h1>Welcome. Please <%= link_to "sign-in", new_user_session_path %> to play.</h1>
  <% end %>
</div>

app/views/games/show.html.erb
  <% if @game.start %>
    <%= render "presentation", object: @game %>

  <% else %>
    <%= render "title" %>
    <%= render "board", object: @board %>
    <%= render "stats", object: @game.hero %>
    <%# Line to debug in prod if problems with the board: <%= render "debug", object: @game %>
  
    <%= render "messages", object: @game.messages %>

    <% if @game.over %>
      <%= render "game_over", object: @game %>
    <% elsif @game.choice %>
      <%= render "choices", object: @game %>
    <% else %>
      <%= render "commands", object: @commands %>
    <% end %>
  <% end %>